# Generated by Django 3.2.3 on 2021-06-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameLand', '0002_auto_20210619_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(help_text="list of items in user's shopping cart.", to='BoardGameLand.Game')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BoardGameLand.user')),
            ],
        ),
    ]
